### ISSUE TITLE
по поводу тестового задания

### ISSUE THREAD

**Issue by oxxxxxy** [qarasssiq/sgs-test-task#1]
Привет, я тож на вакансию от sgs попавс

Можешь, поделиться, что и как у тебя прошло? Что было после тестового задания? Как долго отвечали, проверяли? А потом как было? Ещё одни собес?

Надеюсь, что ответишь.

**Comment by qarasssiq** [comment]
Привет, после тестового задания отвечают примерно в течение недели, если успешно, назначают собес на ближайшее время. Собес один, после него довольно долго ждал обратной связи, недели две.

**Comment by oxxxxxy** [comment]
А как само собеседование проходило? Что было? Просто поговорили?

Много кандидатов было? Мне просто сказали про 200 человек, в чём я сомневаюсь, на гите последние репы две, моя и ещё чела.

И сроки, конечно, у них не оч.

И как в компании у них? Прошел ведь?

**Comment by oxxxxxy** [comment]
Балин, смотрю, ты в другом месте работаешь... Эх, ладно. Спасибо, что ответил, а то я на таком очке чота...

**Comment by qarasssiq** [comment]
На собесе просто поговорили. Про количество кандидатов ничего не знаю.
Проработал у них почти год, мне понравилось, отличная работа для старта.

**Comment by oxxxxxy** [comment]
спасибо, братишка, успокоил меня.

а то я начал думать, что это такая стратегия с затягиванием по времени, чтобы зп задампить, т.к. чел пару недель на ххрю будет в статусе, что ему что-то предложили, другие рекрутеры будут его сливать чисто по этой причине, и ему ничего не останется, кроме как согласиться на меньшее. ну, или это просто троллинг

**Comment by oxxxxxy** [comment]
хм, чота они не спешат, видимо, я сасалити словил

**Comment by oxxxxxy** [comment]
Братишка, а как ты первую работу искал? На сколько готов был по скилам? Ну, так, навскидку? Бэкграунд кодерский хороший был? А то я такой говнокодер, хоть стреляйся, но я исправляюсь.

**Comment by oxxxxxy** [comment]
Спишь?

**Comment by oxxxxxy** [comment]
извини, если сильно докопался... прост очкую, славик.

**Comment by oxxxxxy** [comment]
бля, в шаге, чтобы их матом крыть не начать, они просто молчат, даж не закрыли диалог. крч, это ооооооооч нервозная хрень какая-то.

вопсчем, пойду гавнокодить дальш
спасибо и всё такое.

удачи тебе. щастя здаровя
